<?php


// Editing
$GLOBALS['TL_LANG']['tl_invoice_outbox']['edit']            = array('edit','Edit invoice element details.');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['delete']          = 'Delete this log profile.';
$GLOBALS['TL_LANG']['tl_invoice_outbox']['show']            = array('','detail view');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['invoicePdf']	    = array('','Invoice preview');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['deleteConfirm']   = 'Do yout want delete this entry?';
$GLOBALS['TL_LANG']['tl_invoice_outbox']['customer']        = 'Customers';
$GLOBALS['TL_LANG']['tl_invoice_outbox']['business']        = 'Business';

// Legend
$GLOBALS['TL_LANG']['tl_invoice_outbox']['outbox_legend']      = 'Outbox';

// Labels
$GLOBALS['TL_LANG']['tl_invoice_outbox']['invoiceId'] 	    = array('Invoice ID','');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['tstamp'] 	        = array('Date/Time','The outgoing date and time of the e-mail.');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['customerId'] 	    = array('Customer','The customer who receipt this e-mail.');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['customEmail'] 	= array('E-Mail','The customer e-mail where the invoice document send to.');
$GLOBALS['TL_LANG']['tl_invoice_outbox']['hash'] 		    = array('Hash','The hash value is autogenerated by invoice id and customer company name.');